### ISSUE TITLE
Incomplete codebase

### ISSUE THREAD

**Issue by agrudkow** [MozhganPourKeshavarz/Cost-Free-Incremental-Learning#1]
Hi, if I'm not mistaken some directories/files are lacking from the code base eg. there is no directory _datasets/utils_  or _models/utils_. _PermutedMNIST_ dataset is also lacking from the codebase. Is there any possibility to upload all necessary files for running models? Some example of running the _main.py_ file with all necessary args would also be helpful.

**Comment by agrudkow** [comment]
@MozhganPourKeshavarz

**Comment by mpourkeshavarz** [comment]
@agrudkow Thank you for your interest in our work, the codebase will be updated soon.

**Comment by LiuMengting666** [comment]
> @agrudkow Thank you for your interest in our work, the codebase will be updated soon.

Hello, what an interesting job！it has inspired me a lot, may I ask if the codebase will be updated soon? @MozhganPourKeshavarz

**Comment by mpourkeshavarz** [comment]
This work doesn't include experiments on MNIST360, permuted MNIST, and Rotated MNIST which belong to Domain-IL settings and General Continual Learning setting. You can find out more [here](https://papers.nips.cc/paper/2020/file/b704ea2c39778f07c617f6b7ce480e9e-Paper.pdf). Also, utils files are added to the repo.

**Comment by YAaNnGg** [comment]
Thanks for the updating and sharing.

I notice that there is no training code for MRP so far.  May I ask if it will be updated soon?
