### ISSUE TITLE
missing training code

### ISSUE THREAD

**Issue by YAaNnGg** [MozhganPourKeshavarz/Cost-Free-Incremental-Learning#2]
Thanks for the updating and sharing.

It's an inspiring work, but I notice that there is no training code for MRP so far. May I ask if it will be updated soon?

**Comment by mpourkeshavarz** [comment]
@YAaNnGg 
MRP is a **paradigm** and there is no training step for that. you can get any normal trained network and do the following steps (named Memory Recovery Paradigm (MRP) ) to form a synthesized set:
1. Modeling the Network Output Space
2. Back propagate Through the Network

check Algo. 2 in the paper to find more details.
let me know if you have any further issues.

**Comment by YAaNnGg** [comment]
Thanks for your detailed reply. 

I understand that MRP is a paradigm for optimizing the inputs without network training. I may express what I want to ask wrongly before. Sorry for that. 

In fact, I wonder if there is a complete code for reproducing the result in the paper as described in Alg. 1, because I didn't find it in this repository or tips in the ReadMe (Maybe I miss it uncarefully). Are there any suggestions?

Thanks again.
